const NAME_SPACE = 'DETAIL';

const constants = {
  FETCH_DETAIL_CANCEL: `${NAME_SPACE}/FETCH_DETAIL_CANCEL`,
  FETCH_DETAIL_FAILURE: `${NAME_SPACE}/FETCH_DETAIL_FAILURE`,
  FETCH_DETAIL_REQUEST: `${NAME_SPACE}/FETCH_DETAIL_REQUEST`,
  FETCH_DETAIL_SUCCESS: `${NAME_SPACE}/FETCH_DETAIL_SUCCESS`,
  FETCH_DETAIL: `${NAME_SPACE}/FETCH_DETAIL`,

  FETCH_AUTHOR_CANCEL: `${NAME_SPACE}/FETCH_AUTHOR_CANCEL`,
  FETCH_AUTHOR_FAILURE: `${NAME_SPACE}/FETCH_AUTHOR_FAILURE`,
  FETCH_AUTHOR_REQUEST: `${NAME_SPACE}/FETCH_AUTHOR_REQUEST`,
  FETCH_AUTHOR_SUCCESS: `${NAME_SPACE}/FETCH_AUTHOR_SUCCESS`,
  FETCH_AUTHOR: `${NAME_SPACE}/FETCH_AUTHOR`,

  FILTER: `${NAME_SPACE}/filter`
};

export default constants;
