const NAME_SPACE = 'home';

const constants = {
  FETCH_HOME_CANCEL: `${NAME_SPACE}/FETCH_HOME_CANCEL`,
  FETCH_HOME_FAILURE: `${NAME_SPACE}/FETCH_HOME_FAILURE`,
  FETCH_HOME_REQUEST: `${NAME_SPACE}/FETCH_HOME_REQUEST`,
  FETCH_HOME_SUCCESS: `${NAME_SPACE}/FETCH_HOME_SUCCESS`,
  FETCH_HOME: `${NAME_SPACE}/FETCH_HOME`
};

export default constants;
