const NAME_SPACE = 'home';

const constants = {
  FETCH_HOME_CANCEL: `${NAME_SPACE}/FETCH_HOME_CANCEL`,
  FETCH_HOME_FAILURE: `${NAME_SPACE}/FETCH_HOME_FAILURE`,
  FETCH_HOME_REQUEST: `${NAME_SPACE}/FETCH_HOME_REQUEST`,
  FETCH_HOME_SUCCESS: `${NAME_SPACE}/FETCH_HOME_SUCCESS`,
  FETCH_HOME: `${NAME_SPACE}/FETCH_HOME`,

  SEARCH_CANCEL: `${NAME_SPACE}/SEARCH_CANCEL`,
  SEARCH_FAILURE: `${NAME_SPACE}/SEARCH_FAILURE`,
  SEARCH_REQUEST: `${NAME_SPACE}/SEARCH_REQUEST`,
  SEARCH_SUCCESS: `${NAME_SPACE}/SEARCH_SUCCESS`,
  SEARCH: `${NAME_SPACE}/SEARCH`
};

export default constants;
