const NAME_SPACE = 'app';

const constants = {
  FETCH_SIDEBAR_CANCEL: `${NAME_SPACE}/FETCH_SIDEBAR_CANCEL`,
  FETCH_SIDEBAR_FAILURE: `${NAME_SPACE}/FETCH_SIDEBAR_FAILURE`,
  FETCH_SIDEBAR_REQUEST: `${NAME_SPACE}/FETCH_SIDEBAR_REQUEST`,
  FETCH_SIDEBAR_SUCCESS: `${NAME_SPACE}/FETCH_SIDEBAR_SUCCESS`,
  FETCH_SIDEBAR: `${NAME_SPACE}/FETCH_SIDEBAR`
};

export default constants;
