const NAME_SPACE = 'app';

const constants = {
  FETCH_AUTHORS_CANCEL: `${NAME_SPACE}/FETCH_AUTHORS_CANCEL`,
  FETCH_AUTHORS_FAILURE: `${NAME_SPACE}/FETCH_AUTHORS_FAILURE`,
  FETCH_AUTHORS_REQUEST: `${NAME_SPACE}/FETCH_AUTHORS_REQUEST`,
  FETCH_AUTHORS_SUCCESS: `${NAME_SPACE}/FETCH_AUTHORS_SUCCESS`,
  FETCH_AUTHORS: `${NAME_SPACE}/FETCH_AUTHORS`
};

export default constants;
